User.create!(email:"admin@linkstorage.com", password: "123456789", admin: true)
User.create!(email:"user1@linkstorage.com", password: "123456789", admin: false)
User.create!(email:"user2@linkstorage.com", password: "123456789", admin: false)
User.create!(email:"user3@linkstorage.com", password: "123456789", admin: false)
User.create!(email:"user4@linkstorage.com", password: "123456789", admin: false)
# Bookmark.create!(bookmark: "First bookmark", description: "User 1", user_id: 2)
# Bookmark.create!(bookmark: "Second bookmark", description: "User 1", user_id: 2)
# Bookmark.create!(bookmark: "Third bookmark", description: "User 2", user_id: 3)
# Bookmark.create!(bookmark: "Fourth bookmark", description: "User 2", user_id: 3)
# Bookmark.create!(bookmark: "Fifth bookmark", description: "User 3", user_id: 4)
# Bookmark.create!(bookmark: "Sixth bookmark", description: "User 3", user_id: 4)
# Bookmark.create!(bookmark: "Seventh bookmark", description: "User 4", user_id: 5)
# Bookmark.create!(bookmark: "Eighth bookmark", description: "User 4", user_id: 5)
